// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: helloWorld

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_index1 = NULL;
lv_obj_t * ui_index5 = NULL;
lv_obj_t * ui_index4 = NULL;
lv_obj_t * ui_index2 = NULL;
lv_obj_t * ui_index6 = NULL;
lv_obj_t * ui_index3 = NULL;
lv_obj_t * ui_labelSysInit = NULL;
lv_obj_t * ui_labelPlatterRPM = NULL;
lv_obj_t * ui_labelPlatterHz = NULL;
lv_obj_t * ui_labelFrameCount = NULL;
lv_obj_t * ui_labelFrameT = NULL;
lv_obj_t * ui_labelFrameOnT = NULL;
lv_obj_t * ui_labelState = NULL;
lv_obj_t * ui_index11 = NULL;
lv_obj_t * ui_labelMotorEnabled = NULL;
lv_obj_t * ui_index12 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_index10 = NULL;
lv_obj_t * ui_labelRotPeriod = NULL;
lv_obj_t * ui_index13 = NULL;
lv_obj_t * ui_labelStrobeEnabled = NULL;
lv_obj_t * ui_index19 = NULL;
lv_obj_t * ui_labelTemp1 = NULL;
lv_obj_t * ui_labelTemp1Unit = NULL;
lv_obj_t * ui_index20 = NULL;
lv_obj_t * ui_labelTemp2 = NULL;
lv_obj_t * ui_labelTemp2Unit = NULL;
lv_obj_t * ui_index21 = NULL;
lv_obj_t * ui_labelLight1 = NULL;
lv_obj_t * ui_index22 = NULL;
lv_obj_t * ui_labelLight2 = NULL;
lv_obj_t * ui_index7 = NULL;
lv_obj_t * ui_labelStrobeMode = NULL;
lv_obj_t * ui_index8 = NULL;
lv_obj_t * ui_labelMotorMode = NULL;
lv_obj_t * ui_index14 = NULL;
lv_obj_t * ui_index15 = NULL;
lv_obj_t * ui_labelMotorMode1 = NULL;
lv_obj_t * ui_labelStealthChop = NULL;
lv_obj_t * ui_index0 = NULL;
lv_obj_t * ui_labelPlatterID = NULL;
lv_obj_t * ui_index9 = NULL;
lv_obj_t * ui_labelPlatterID1 = NULL;
lv_obj_t * ui_index18 = NULL;
lv_obj_t * ui_labelPlatterID2 = NULL;
lv_obj_t * ui_index16 = NULL;
lv_obj_t * ui_labelFan1 = NULL;
lv_obj_t * ui_labelFan2 = NULL;
lv_obj_t * ui_index17 = NULL;
lv_obj_t * ui_labelPotValue = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 530);
    lv_obj_set_height(ui_Container1, 1643);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 698);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Container1, LV_DIR_VER);

    ui_index1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index1, -87);
    lv_obj_set_y(ui_index1, -516);
    lv_obj_set_align(ui_index1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index1, "Sys Init; State:");
    lv_obj_set_style_text_font(ui_index1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index1, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index1, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index1, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_index5 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index5, -79);
    lv_obj_set_y(ui_index5, -395);
    lv_obj_set_align(ui_index5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index5, "Platter RPM:");
    lv_obj_set_style_text_font(ui_index5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index5, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index5, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index5, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_index4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index4, -63);
    lv_obj_set_y(ui_index4, -425);
    lv_obj_set_align(ui_index4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index4, "Platter Hz:");
    lv_obj_set_style_text_font(ui_index4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index4, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index4, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index4, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_index2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index2, -86);
    lv_obj_set_y(ui_index2, -486);
    lv_obj_set_align(ui_index2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index2, "Frame Count:");
    lv_obj_set_style_text_font(ui_index2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index2, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index2, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index2, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_index6 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index6, -83);
    lv_obj_set_y(ui_index6, -364);
    lv_obj_set_align(ui_index6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index6, "Frame T (us):");
    lv_obj_set_style_text_font(ui_index6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index6, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index6, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index6, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index6, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index6, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_index3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index3, -82);
    lv_obj_set_y(ui_index3, -456);
    lv_obj_set_align(ui_index3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index3, "Frame ON %:");
    lv_obj_set_style_text_font(ui_index3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index3, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index3, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index3, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelSysInit = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelSysInit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSysInit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSysInit, 64);
    lv_obj_set_y(ui_labelSysInit, -514);
    lv_obj_set_align(ui_labelSysInit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSysInit, "NO");
    lv_obj_set_style_text_color(ui_labelSysInit, lv_color_hex(0x9B1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSysInit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSysInit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterRPM = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterRPM, 77);
    lv_obj_set_y(ui_labelPlatterRPM, -392);
    lv_obj_set_align(ui_labelPlatterRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterRPM, "123.56");
    lv_obj_set_style_text_color(ui_labelPlatterRPM, lv_color_hex(0x158B25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlatterRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlatterRPM, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterHz = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterHz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterHz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterHz, 79);
    lv_obj_set_y(ui_labelPlatterHz, -423);
    lv_obj_set_align(ui_labelPlatterHz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterHz, "12.34");
    lv_obj_set_style_text_color(ui_labelPlatterHz, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlatterHz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlatterHz, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFrameCount = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFrameCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFrameCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFrameCount, 63);
    lv_obj_set_y(ui_labelFrameCount, -483);
    lv_obj_set_align(ui_labelFrameCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFrameCount, "123");
    lv_obj_set_style_text_color(ui_labelFrameCount, lv_color_hex(0x2F8DD6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFrameCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFrameCount, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_labelFrameCount, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_labelFrameCount, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_labelFrameCount, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_labelFrameCount, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_labelFrameCount, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_labelFrameCount, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_labelFrameCount, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_labelFrameCount, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_labelFrameCount, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelFrameT = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFrameT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFrameT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFrameT, 99);
    lv_obj_set_y(ui_labelFrameT, -362);
    lv_obj_set_align(ui_labelFrameT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFrameT, "123,456");
    lv_obj_set_style_text_color(ui_labelFrameT, lv_color_hex(0x923EBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFrameT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFrameT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFrameOnT = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFrameOnT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFrameOnT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFrameOnT, 83);
    lv_obj_set_y(ui_labelFrameOnT, -452);
    lv_obj_set_align(ui_labelFrameOnT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFrameOnT, "1.02%");
    lv_obj_set_style_text_color(ui_labelFrameOnT, lv_color_hex(0x2F8ED6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFrameOnT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFrameOnT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_labelFrameOnT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_labelFrameOnT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_labelFrameOnT, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_labelFrameOnT, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_labelFrameOnT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_labelFrameOnT, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_labelFrameOnT, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_labelFrameOnT, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_labelFrameOnT, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelState = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelState, 166);
    lv_obj_set_y(ui_labelState, -512);
    lv_obj_set_align(ui_labelState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelState, "OK");
    lv_obj_set_style_text_color(ui_labelState, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelState, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index11 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index11, -99);
    lv_obj_set_y(ui_index11, -211);
    lv_obj_set_align(ui_index11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index11, "Motor Enabled:");
    lv_obj_set_style_text_font(ui_index11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index11, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index11, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index11, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index11, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index11, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelMotorEnabled = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelMotorEnabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotorEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotorEnabled, 76);
    lv_obj_set_y(ui_labelMotorEnabled, -211);
    lv_obj_set_align(ui_labelMotorEnabled, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotorEnabled, "YES");
    lv_obj_set_style_text_color(ui_labelMotorEnabled, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelMotorEnabled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelMotorEnabled, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index12 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index12, -107);
    lv_obj_set_y(ui_index12, -181);
    lv_obj_set_align(ui_index12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index12, "Motor Direction:");
    lv_obj_set_style_text_font(ui_index12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index12, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index12, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index12, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index12, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index12, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 88);
    lv_obj_set_y(ui_Label4, -179);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "CCW");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xC4D31F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index10 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index10, -105);
    lv_obj_set_y(ui_index10, -242);
    lv_obj_set_align(ui_index10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index10, "Rot Period (ms):");
    lv_obj_set_style_text_font(ui_index10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index10, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index10, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index10, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index10, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index10, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelRotPeriod = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelRotPeriod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRotPeriod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelRotPeriod, 85);
    lv_obj_set_y(ui_labelRotPeriod, -242);
    lv_obj_set_align(ui_labelRotPeriod, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRotPeriod, "1,000");
    lv_obj_set_style_text_font(ui_labelRotPeriod, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index13 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index13, -104);
    lv_obj_set_y(ui_index13, -150);
    lv_obj_set_align(ui_index13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index13, "Strobe Enabled:");
    lv_obj_set_style_text_font(ui_index13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index13, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index13, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index13, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index13, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index13, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelStrobeEnabled = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelStrobeEnabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStrobeEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStrobeEnabled, 85);
    lv_obj_set_y(ui_labelStrobeEnabled, -148);
    lv_obj_set_align(ui_labelStrobeEnabled, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStrobeEnabled, "YES");
    lv_obj_set_style_text_color(ui_labelStrobeEnabled, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStrobeEnabled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStrobeEnabled, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index19 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index19, -97);
    lv_obj_set_y(ui_index19, 35);
    lv_obj_set_align(ui_index19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index19, "Temp Sensor 1:");
    lv_obj_set_style_text_font(ui_index19, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index19, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index19, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index19, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index19, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index19, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index19, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index19, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index19, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelTemp1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp1, 83);
    lv_obj_set_y(ui_labelTemp1, 34);
    lv_obj_set_align(ui_labelTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp1, "71.9");
    lv_obj_set_style_text_font(ui_labelTemp1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp1Unit = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp1Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp1Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp1Unit, 135);
    lv_obj_set_y(ui_labelTemp1Unit, 33);
    lv_obj_set_align(ui_labelTemp1Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp1Unit, "F");
    lv_obj_set_style_text_color(ui_labelTemp1Unit, lv_color_hex(0xB44F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp1Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp1Unit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index20 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index20, -99);
    lv_obj_set_y(ui_index20, 66);
    lv_obj_set_align(ui_index20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index20, "Temp Sensor 2:");
    lv_obj_set_style_text_font(ui_index20, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index20, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index20, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index20, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index20, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index20, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index20, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index20, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index20, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelTemp2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp2, 83);
    lv_obj_set_y(ui_labelTemp2, 66);
    lv_obj_set_align(ui_labelTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp2, "71.9");
    lv_obj_set_style_text_font(ui_labelTemp2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp2Unit = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp2Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp2Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp2Unit, 135);
    lv_obj_set_y(ui_labelTemp2Unit, 67);
    lv_obj_set_align(ui_labelTemp2Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp2Unit, "F");
    lv_obj_set_style_text_color(ui_labelTemp2Unit, lv_color_hex(0xB44F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp2Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp2Unit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index21 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index21, -91);
    lv_obj_set_y(ui_index21, 97);
    lv_obj_set_align(ui_index21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index21, "Light Sensor 1:");
    lv_obj_set_style_text_font(ui_index21, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index21, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index21, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index21, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index21, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index21, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelLight1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelLight1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLight1, 127);
    lv_obj_set_y(ui_labelLight1, 97);
    lv_obj_set_align(ui_labelLight1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLight1, "light data");
    lv_obj_set_style_text_color(ui_labelLight1, lv_color_hex(0xB24CD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLight1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index22 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index22, -94);
    lv_obj_set_y(ui_index22, 129);
    lv_obj_set_align(ui_index22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index22, "Light Sensor 2:");
    lv_obj_set_style_text_font(ui_index22, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index22, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index22, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index22, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index22, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index22, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index22, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index22, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index22, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelLight2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelLight2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLight2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLight2, 128);
    lv_obj_set_y(ui_labelLight2, 127);
    lv_obj_set_align(ui_labelLight2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLight2, "light data");
    lv_obj_set_style_text_color(ui_labelLight2, lv_color_hex(0xB24CD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLight2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index7 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index7, -83);
    lv_obj_set_y(ui_index7, -333);
    lv_obj_set_align(ui_index7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index7, "strobe mode:");
    lv_obj_set_style_text_font(ui_index7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index7, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index7, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index7, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index7, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index7, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelStrobeMode = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelStrobeMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStrobeMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStrobeMode, 96);
    lv_obj_set_y(ui_labelStrobeMode, -333);
    lv_obj_set_align(ui_labelStrobeMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStrobeMode, "classic");
    lv_obj_set_style_text_color(ui_labelStrobeMode, lv_color_hex(0x528DDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStrobeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStrobeMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index8 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index8, -82);
    lv_obj_set_y(ui_index8, -303);
    lv_obj_set_align(ui_index8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index8, "motor mode:");
    lv_obj_set_style_text_font(ui_index8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index8, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index8, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index8, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index8, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index8, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelMotorMode = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelMotorMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotorMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotorMode, 95);
    lv_obj_set_y(ui_labelMotorMode, -304);
    lv_obj_set_align(ui_labelMotorMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotorMode, "classic");
    lv_obj_set_style_text_color(ui_labelMotorMode, lv_color_hex(0x528DDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelMotorMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelMotorMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index14 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index14, -120);
    lv_obj_set_y(ui_index14, -120);
    lv_obj_set_align(ui_index14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index14, "motor step mode:");
    lv_obj_set_style_text_font(ui_index14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index14, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index14, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index14, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index14, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index14, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index14, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index14, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index14, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_index15 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index15, -80);
    lv_obj_set_y(ui_index15, -89);
    lv_obj_set_align(ui_index15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index15, "stealthchop:");
    lv_obj_set_style_text_font(ui_index15, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index15, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index15, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index15, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index15, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index15, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelMotorMode1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelMotorMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotorMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotorMode1, 110);
    lv_obj_set_y(ui_labelMotorMode1, -118);
    lv_obj_set_align(ui_labelMotorMode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotorMode1, "full step");
    lv_obj_set_style_text_font(ui_labelMotorMode1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStealthChop = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelStealthChop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStealthChop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStealthChop, 78);
    lv_obj_set_y(ui_labelStealthChop, -88);
    lv_obj_set_align(ui_labelStealthChop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStealthChop, "YES");
    lv_obj_set_style_text_color(ui_labelStealthChop, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStealthChop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStealthChop, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index0 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index0, -60);
    lv_obj_set_y(ui_index0, -546);
    lv_obj_set_align(ui_index0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index0, "Platter ID:");
    lv_obj_set_style_text_font(ui_index0, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_index0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_index0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index0, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index0, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index0, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index0, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index0, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index0, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index0, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index0, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelPlatterID = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterID, 102);
    lv_obj_set_y(ui_labelPlatterID, -544);
    lv_obj_set_align(ui_labelPlatterID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterID, "10101010");
    lv_obj_set_style_text_font(ui_labelPlatterID, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index9 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index9, -99);
    lv_obj_set_y(ui_index9, -272);
    lv_obj_set_align(ui_index9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index9, "Platter Loaded:");
    lv_obj_set_style_text_font(ui_index9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index9, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index9, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index9, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index9, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index9, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelPlatterID1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterID1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterID1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterID1, 109);
    lv_obj_set_y(ui_labelPlatterID1, -274);
    lv_obj_set_align(ui_labelPlatterID1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterID1, "not imp.");
    lv_obj_set_style_text_color(ui_labelPlatterID1, lv_color_hex(0xD73333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlatterID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlatterID1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index18 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index18, -116);
    lv_obj_set_y(ui_index18, 2);
    lv_obj_set_align(ui_index18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index18, "heartBeat T (ms):");
    lv_obj_set_style_text_font(ui_index18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index18, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index18, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index18, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index18, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index18, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index18, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index18, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index18, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelPlatterID2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterID2, 76);
    lv_obj_set_y(ui_labelPlatterID2, 3);
    lv_obj_set_align(ui_labelPlatterID2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterID2, "65");
    lv_obj_set_style_text_font(ui_labelPlatterID2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index16 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index16, -80);
    lv_obj_set_y(ui_index16, -58);
    lv_obj_set_align(ui_index16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index16, "Fan 1 ; Fan 2:");
    lv_obj_set_style_text_font(ui_index16, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index16, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index16, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index16, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index16, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index16, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index16, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index16, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index16, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelFan1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFan1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFan1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFan1, 79);
    lv_obj_set_y(ui_labelFan1, -58);
    lv_obj_set_align(ui_labelFan1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFan1, "ON");
    lv_obj_set_style_text_color(ui_labelFan1, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFan1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFan1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFan2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFan2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFan2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFan2, 194);
    lv_obj_set_y(ui_labelFan2, -56);
    lv_obj_set_align(ui_labelFan2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFan2, "ON");
    lv_obj_set_style_text_color(ui_labelFan2, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFan2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFan2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_index17 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_index17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index17, -61);
    lv_obj_set_y(ui_index17, -28);
    lv_obj_set_align(ui_index17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_index17, "pot Value:");
    lv_obj_set_style_text_font(ui_index17, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_index17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_index17, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_radius(ui_index17, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_index17, lv_color_hex(0xDA97F3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_index17, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_index17, lv_color_hex(0x751B8F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_index17, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_index17, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_index17, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_labelPotValue = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPotValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPotValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPotValue, 98);
    lv_obj_set_y(ui_labelPotValue, -28);
    lv_obj_set_align(ui_labelPotValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPotValue, "10000");
    lv_obj_set_style_text_color(ui_labelPotValue, lv_color_hex(0x8718E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPotValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPotValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 115);
    lv_obj_set_y(ui_Label28, -513);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "||");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Container1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 421);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, -2);
    lv_obj_set_y(ui_Bar1, 175);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Switch1 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_Switch1, 102);
    lv_obj_set_height(ui_Switch1, 48);
    lv_obj_set_x(ui_Switch1, -163);
    lv_obj_set_y(ui_Switch1, 418);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Slider1 = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 461);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 3);
    lv_obj_set_y(ui_Slider1, 531);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Spinner1 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, -4);
    lv_obj_set_y(ui_Spinner1, 416);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Container1);
    lv_obj_set_width(ui_Chart1, 453);
    lv_obj_set_height(ui_Chart1, 100);
    lv_obj_set_x(ui_Chart1, -1);
    lv_obj_set_y(ui_Chart1, 261);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 139);
    lv_obj_set_y(ui_Label1, -60);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "||");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 459);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 3);
    lv_obj_set_y(ui_Slider2, 502);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xAA2DB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_Switch2, 102);
    lv_obj_set_height(ui_Switch2, 48);
    lv_obj_set_x(ui_Switch2, 154);
    lv_obj_set_y(ui_Switch2, 418);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Image1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image1, &ui_img_zoetrope_splash_screen2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -697);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_index1 = NULL;
    ui_index5 = NULL;
    ui_index4 = NULL;
    ui_index2 = NULL;
    ui_index6 = NULL;
    ui_index3 = NULL;
    ui_labelSysInit = NULL;
    ui_labelPlatterRPM = NULL;
    ui_labelPlatterHz = NULL;
    ui_labelFrameCount = NULL;
    ui_labelFrameT = NULL;
    ui_labelFrameOnT = NULL;
    ui_labelState = NULL;
    ui_index11 = NULL;
    ui_labelMotorEnabled = NULL;
    ui_index12 = NULL;
    ui_Label4 = NULL;
    ui_index10 = NULL;
    ui_labelRotPeriod = NULL;
    ui_index13 = NULL;
    ui_labelStrobeEnabled = NULL;
    ui_index19 = NULL;
    ui_labelTemp1 = NULL;
    ui_labelTemp1Unit = NULL;
    ui_index20 = NULL;
    ui_labelTemp2 = NULL;
    ui_labelTemp2Unit = NULL;
    ui_index21 = NULL;
    ui_labelLight1 = NULL;
    ui_index22 = NULL;
    ui_labelLight2 = NULL;
    ui_index7 = NULL;
    ui_labelStrobeMode = NULL;
    ui_index8 = NULL;
    ui_labelMotorMode = NULL;
    ui_index14 = NULL;
    ui_index15 = NULL;
    ui_labelMotorMode1 = NULL;
    ui_labelStealthChop = NULL;
    ui_index0 = NULL;
    ui_labelPlatterID = NULL;
    ui_index9 = NULL;
    ui_labelPlatterID1 = NULL;
    ui_index18 = NULL;
    ui_labelPlatterID2 = NULL;
    ui_index16 = NULL;
    ui_labelFan1 = NULL;
    ui_labelFan2 = NULL;
    ui_index17 = NULL;
    ui_labelPotValue = NULL;
    ui_Label28 = NULL;
    ui_Bar1 = NULL;
    ui_Switch1 = NULL;
    ui_Slider1 = NULL;
    ui_Spinner1 = NULL;
    ui_Chart1 = NULL;
    ui_Label1 = NULL;
    ui_Slider2 = NULL;
    ui_Switch2 = NULL;
    ui_Image1 = NULL;

}
