// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: helloWorld

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_index1;
extern lv_obj_t * ui_index5;
extern lv_obj_t * ui_index4;
extern lv_obj_t * ui_index2;
extern lv_obj_t * ui_index6;
extern lv_obj_t * ui_index3;
extern lv_obj_t * ui_labelSysInit;
extern lv_obj_t * ui_labelPlatterRPM;
extern lv_obj_t * ui_labelPlatterHz;
extern lv_obj_t * ui_labelFrameCount;
extern lv_obj_t * ui_labelFrameT;
extern lv_obj_t * ui_labelFrameOnT;
extern lv_obj_t * ui_labelState;
extern lv_obj_t * ui_index11;
extern lv_obj_t * ui_labelMotorEnabled;
extern lv_obj_t * ui_index12;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_index10;
extern lv_obj_t * ui_labelRotPeriod;
extern lv_obj_t * ui_index13;
extern lv_obj_t * ui_labelStrobeEnabled;
extern lv_obj_t * ui_index19;
extern lv_obj_t * ui_labelTemp1;
extern lv_obj_t * ui_labelTemp1Unit;
extern lv_obj_t * ui_index20;
extern lv_obj_t * ui_labelTemp2;
extern lv_obj_t * ui_labelTemp2Unit;
extern lv_obj_t * ui_index21;
extern lv_obj_t * ui_labelLight1;
extern lv_obj_t * ui_index22;
extern lv_obj_t * ui_labelLight2;
extern lv_obj_t * ui_index7;
extern lv_obj_t * ui_labelStrobeMode;
extern lv_obj_t * ui_index8;
extern lv_obj_t * ui_labelMotorMode;
extern lv_obj_t * ui_index14;
extern lv_obj_t * ui_index15;
extern lv_obj_t * ui_labelMotorMode1;
extern lv_obj_t * ui_labelStealthChop;
extern lv_obj_t * ui_index0;
extern lv_obj_t * ui_labelPlatterID;
extern lv_obj_t * ui_index9;
extern lv_obj_t * ui_labelPlatterID1;
extern lv_obj_t * ui_index18;
extern lv_obj_t * ui_labelPlatterID2;
extern lv_obj_t * ui_index16;
extern lv_obj_t * ui_labelFan1;
extern lv_obj_t * ui_labelFan2;
extern lv_obj_t * ui_index17;
extern lv_obj_t * ui_labelPotValue;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

