// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Hello World Circular

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_LabelPlatterID = NULL;
lv_obj_t * ui_LabelAutoRun = NULL;
lv_obj_t * ui_labelStrobeMode = NULL;
lv_obj_t * ui_LabelFameCount = NULL;
lv_obj_t * ui_LabelRotDir = NULL;
lv_obj_t * ui_labelAmbLight = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 462);
    lv_obj_set_height(ui_Spinner1, 469);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 4);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x4AA034), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -74);
    lv_obj_set_y(ui_Label1, -91);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Platter ID:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -98);
    lv_obj_set_y(ui_Label2, 11);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Frame Count: ");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -101);
    lv_obj_set_y(ui_Label3, -23);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Strobe Mode:");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -75);
    lv_obj_set_y(ui_Label4, -55);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Auto Run:");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -96);
    lv_obj_set_y(ui_Label5, 44);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Rotation Dir:");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -89);
    lv_obj_set_y(ui_Label6, 76);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Amb. Light:");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPlatterID = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelPlatterID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPlatterID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPlatterID, 81);
    lv_obj_set_y(ui_LabelPlatterID, -89);
    lv_obj_set_align(ui_LabelPlatterID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPlatterID, "12345678");
    lv_obj_set_style_text_color(ui_LabelPlatterID, lv_color_hex(0x34A030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPlatterID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPlatterID, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAutoRun = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelAutoRun, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAutoRun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAutoRun, 45);
    lv_obj_set_y(ui_LabelAutoRun, -54);
    lv_obj_set_align(ui_LabelAutoRun, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAutoRun, "YES");
    lv_obj_set_style_text_color(ui_LabelAutoRun, lv_color_hex(0x34A030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAutoRun, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAutoRun, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStrobeMode = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelStrobeMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStrobeMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStrobeMode, 65);
    lv_obj_set_y(ui_labelStrobeMode, -23);
    lv_obj_set_align(ui_labelStrobeMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStrobeMode, "Classic");
    lv_obj_set_style_text_color(ui_labelStrobeMode, lv_color_hex(0xAA47B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStrobeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStrobeMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFameCount = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelFameCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFameCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFameCount, 36);
    lv_obj_set_y(ui_LabelFameCount, 12);
    lv_obj_set_align(ui_LabelFameCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFameCount, "20");
    lv_obj_set_style_text_color(ui_LabelFameCount, lv_color_hex(0x32B9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFameCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFameCount, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRotDir = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelRotDir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRotDir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRotDir, 53);
    lv_obj_set_y(ui_LabelRotDir, 44);
    lv_obj_set_align(ui_LabelRotDir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRotDir, "CCW");
    lv_obj_set_style_text_color(ui_LabelRotDir, lv_color_hex(0x9A51C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRotDir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRotDir, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelAmbLight = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelAmbLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelAmbLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelAmbLight, 48);
    lv_obj_set_y(ui_labelAmbLight, 78);
    lv_obj_set_align(ui_labelAmbLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelAmbLight, "Dim");
    lv_obj_set_style_text_color(ui_labelAmbLight, lv_color_hex(0xC68E13), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelAmbLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelAmbLight, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Spinner1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_LabelPlatterID = NULL;
    ui_LabelAutoRun = NULL;
    ui_labelStrobeMode = NULL;
    ui_LabelFameCount = NULL;
    ui_LabelRotDir = NULL;
    ui_labelAmbLight = NULL;

}
