M48
; DRILL file {KiCad 9.0.6} date 2025-12-07T15:07:31-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-07T15:07:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X213.637Y-75.505
X213.637Y-81.855
X246.1Y-75.565
X246.1Y-81.915
T2
X224.95Y-83.1
M30
