// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: helloWorld

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_labelSysInit = NULL;
lv_obj_t * ui_labelPlatterRPM = NULL;
lv_obj_t * ui_labelPlatterHz = NULL;
lv_obj_t * ui_labelFrameCount = NULL;
lv_obj_t * ui_labelFrameT = NULL;
lv_obj_t * ui_labelFrameOnT = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_labelState = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_labelMotorEnabled = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_labelRotPeriod = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_labelStrobeEnabled = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_labelTemp1 = NULL;
lv_obj_t * ui_labelTemp1Unit = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_labelTemp2 = NULL;
lv_obj_t * ui_labelTemp2Unit = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_labelLight1 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_labelLight2 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_labelStrobeMode = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_labelMotorMode = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_labelMotorMode1 = NULL;
lv_obj_t * ui_labelStealthChop = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_labelPlatterID = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_labelPlatterID1 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_labelPlatterID2 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_labelFan1 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_labelFan2 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_labelPotValue = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 41);
    lv_obj_set_height(ui_Spinner2, 36);
    lv_obj_set_x(ui_Spinner2, 244);
    lv_obj_set_y(ui_Spinner2, -92);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x010F01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x1F8015), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 530);
    lv_obj_set_height(ui_Container1, 1076);
    lv_obj_set_x(ui_Container1, -3);
    lv_obj_set_y(ui_Container1, 173);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Container1, LV_DIR_VER);

    ui_Label6 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -25);
    lv_obj_set_y(ui_Label6, -266);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Sys Init: ");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -63);
    lv_obj_set_y(ui_Label7, -236);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Platter RPM: ");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -47);
    lv_obj_set_y(ui_Label8, -206);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Platter Hz: ");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -52);
    lv_obj_set_y(ui_Label9, -176);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Frame Cnt: ");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -66);
    lv_obj_set_y(ui_Label10, -146);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Frame T (us): ");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -95);
    lv_obj_set_y(ui_Label11, -114);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Frame ON T (uS): ");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSysInit = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelSysInit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSysInit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSysInit, 85);
    lv_obj_set_y(ui_labelSysInit, -265);
    lv_obj_set_align(ui_labelSysInit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSysInit, "NO");
    lv_obj_set_style_text_color(ui_labelSysInit, lv_color_hex(0x9B1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSysInit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSysInit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterRPM = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterRPM, 129);
    lv_obj_set_y(ui_labelPlatterRPM, -236);
    lv_obj_set_align(ui_labelPlatterRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterRPM, "123.56");
    lv_obj_set_style_text_color(ui_labelPlatterRPM, lv_color_hex(0x158B25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlatterRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlatterRPM, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterHz = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterHz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterHz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterHz, 122);
    lv_obj_set_y(ui_labelPlatterHz, -207);
    lv_obj_set_align(ui_labelPlatterHz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterHz, "12.34");
    lv_obj_set_style_text_color(ui_labelPlatterHz, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlatterHz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlatterHz, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFrameCount = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFrameCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFrameCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFrameCount, 90);
    lv_obj_set_y(ui_labelFrameCount, -177);
    lv_obj_set_align(ui_labelFrameCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFrameCount, "123");
    lv_obj_set_style_text_color(ui_labelFrameCount, lv_color_hex(0x2F8DD6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFrameCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFrameCount, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFrameT = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFrameT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFrameT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFrameT, 135);
    lv_obj_set_y(ui_labelFrameT, -145);
    lv_obj_set_align(ui_labelFrameT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFrameT, "123,456");
    lv_obj_set_style_text_color(ui_labelFrameT, lv_color_hex(0x923EBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFrameT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFrameT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFrameOnT = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFrameOnT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFrameOnT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFrameOnT, 133);
    lv_obj_set_y(ui_labelFrameOnT, -114);
    lv_obj_set_align(ui_labelFrameOnT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFrameOnT, "12,345");
    lv_obj_set_style_text_color(ui_labelFrameOnT, lv_color_hex(0x2F8ED6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFrameOnT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFrameOnT, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -74);
    lv_obj_set_y(ui_Label1, -83);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "System State:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelState = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelState, 98);
    lv_obj_set_y(ui_labelState, -82);
    lv_obj_set_align(ui_labelState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelState, "OK");
    lv_obj_set_style_text_color(ui_labelState, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelState, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -87);
    lv_obj_set_y(ui_Label2, -52);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Motor Enabled:");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMotorEnabled = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelMotorEnabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotorEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotorEnabled, 105);
    lv_obj_set_y(ui_labelMotorEnabled, -53);
    lv_obj_set_align(ui_labelMotorEnabled, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotorEnabled, "YES");
    lv_obj_set_style_text_color(ui_labelMotorEnabled, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelMotorEnabled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelMotorEnabled, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -97);
    lv_obj_set_y(ui_Label3, -21);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Motor Direction:");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 112);
    lv_obj_set_y(ui_Label4, -20);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "CCW");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xC4D31F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -96);
    lv_obj_set_y(ui_Label5, 8);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Rot Period (ms):");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRotPeriod = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelRotPeriod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRotPeriod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelRotPeriod, 133);
    lv_obj_set_y(ui_labelRotPeriod, 11);
    lv_obj_set_align(ui_labelRotPeriod, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRotPeriod, "100,000");
    lv_obj_set_style_text_font(ui_labelRotPeriod, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -95);
    lv_obj_set_y(ui_Label13, 40);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Strobe Enabled:");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -95);
    lv_obj_set_y(ui_Label12, 40);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Strobe Enabled:");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStrobeEnabled = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelStrobeEnabled, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStrobeEnabled, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStrobeEnabled, 107);
    lv_obj_set_y(ui_labelStrobeEnabled, 41);
    lv_obj_set_align(ui_labelStrobeEnabled, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStrobeEnabled, "YES");
    lv_obj_set_style_text_color(ui_labelStrobeEnabled, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStrobeEnabled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStrobeEnabled, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -87);
    lv_obj_set_y(ui_Label14, 70);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Temp Sensor 1:");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp1, 98);
    lv_obj_set_y(ui_labelTemp1, 72);
    lv_obj_set_align(ui_labelTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp1, "71.9");
    lv_obj_set_style_text_font(ui_labelTemp1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp1Unit = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp1Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp1Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp1Unit, 144);
    lv_obj_set_y(ui_labelTemp1Unit, 72);
    lv_obj_set_align(ui_labelTemp1Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp1Unit, "F");
    lv_obj_set_style_text_color(ui_labelTemp1Unit, lv_color_hex(0xB44F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp1Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp1Unit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -91);
    lv_obj_set_y(ui_Label15, 100);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Temp Sensor 2:");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp2, 100);
    lv_obj_set_y(ui_labelTemp2, 102);
    lv_obj_set_align(ui_labelTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp2, "71.9");
    lv_obj_set_style_text_font(ui_labelTemp2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp2Unit = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelTemp2Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp2Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp2Unit, 144);
    lv_obj_set_y(ui_labelTemp2Unit, 102);
    lv_obj_set_align(ui_labelTemp2Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp2Unit, "F");
    lv_obj_set_style_text_color(ui_labelTemp2Unit, lv_color_hex(0xB44F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp2Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp2Unit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -85);
    lv_obj_set_y(ui_Label16, 129);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Light Sensor 1:");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelLight1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelLight1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLight1, 142);
    lv_obj_set_y(ui_labelLight1, 133);
    lv_obj_set_align(ui_labelLight1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLight1, "light data");
    lv_obj_set_style_text_color(ui_labelLight1, lv_color_hex(0xB24CD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLight1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -87);
    lv_obj_set_y(ui_Label17, 159);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Light Sensor 2:");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelLight2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelLight2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLight2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLight2, 143);
    lv_obj_set_y(ui_labelLight2, 162);
    lv_obj_set_align(ui_labelLight2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLight2, "light data");
    lv_obj_set_style_text_color(ui_labelLight2, lv_color_hex(0xB24CD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLight2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -76);
    lv_obj_set_y(ui_Label18, 190);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "strobe mode:");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStrobeMode = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelStrobeMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStrobeMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStrobeMode, 121);
    lv_obj_set_y(ui_labelStrobeMode, 193);
    lv_obj_set_align(ui_labelStrobeMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStrobeMode, "classic");
    lv_obj_set_style_text_color(ui_labelStrobeMode, lv_color_hex(0x528DDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStrobeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStrobeMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -76);
    lv_obj_set_y(ui_Label19, 221);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "motor mode:");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMotorMode = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelMotorMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotorMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotorMode, 121);
    lv_obj_set_y(ui_labelMotorMode, 223);
    lv_obj_set_align(ui_labelMotorMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotorMode, "classic");
    lv_obj_set_style_text_color(ui_labelMotorMode, lv_color_hex(0x528DDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelMotorMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelMotorMode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -114);
    lv_obj_set_y(ui_Label20, 252);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "motor step mode:");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -74);
    lv_obj_set_y(ui_Label21, 284);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "stealthchop:");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMotorMode1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelMotorMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMotorMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMotorMode1, 124);
    lv_obj_set_y(ui_labelMotorMode1, 253);
    lv_obj_set_align(ui_labelMotorMode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMotorMode1, "full step");
    lv_obj_set_style_text_font(ui_labelMotorMode1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelStealthChop = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelStealthChop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelStealthChop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelStealthChop, 124);
    lv_obj_set_y(ui_labelStealthChop, 284);
    lv_obj_set_align(ui_labelStealthChop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelStealthChop, "YES");
    lv_obj_set_style_text_color(ui_labelStealthChop, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelStealthChop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelStealthChop, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -56);
    lv_obj_set_y(ui_Label22, 313);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Platter ID:");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterID = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterID, 125);
    lv_obj_set_y(ui_labelPlatterID, 313);
    lv_obj_set_align(ui_labelPlatterID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterID, "10101010");
    lv_obj_set_style_text_font(ui_labelPlatterID, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -96);
    lv_obj_set_y(ui_Label23, 343);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Platter Loaded:");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterID1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterID1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterID1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterID1, 127);
    lv_obj_set_y(ui_labelPlatterID1, 342);
    lv_obj_set_align(ui_labelPlatterID1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterID1, "not imp.");
    lv_obj_set_style_text_color(ui_labelPlatterID1, lv_color_hex(0xD73333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlatterID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlatterID1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -111);
    lv_obj_set_y(ui_Label24, 374);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "heartBeat T (ms):");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlatterID2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPlatterID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlatterID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlatterID2, 86);
    lv_obj_set_y(ui_labelPlatterID2, 374);
    lv_obj_set_align(ui_labelPlatterID2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlatterID2, "65");
    lv_obj_set_style_text_font(ui_labelPlatterID2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -23);
    lv_obj_set_y(ui_Label25, 406);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Fan 1:");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFan1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFan1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFan1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFan1, 86);
    lv_obj_set_y(ui_labelFan1, 404);
    lv_obj_set_align(ui_labelFan1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFan1, "ON");
    lv_obj_set_style_text_color(ui_labelFan1, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFan1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFan1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -23);
    lv_obj_set_y(ui_Label26, 437);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Fan 2:");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFan2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelFan2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFan2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFan2, 85);
    lv_obj_set_y(ui_labelFan2, 437);
    lv_obj_set_align(ui_labelFan2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFan2, "ON");
    lv_obj_set_style_text_color(ui_labelFan2, lv_color_hex(0x158C25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelFan2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelFan2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -55);
    lv_obj_set_y(ui_Label27, 466);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "pot Value:");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPotValue = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelPotValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPotValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPotValue, 105);
    lv_obj_set_y(ui_labelPotValue, 467);
    lv_obj_set_align(ui_labelPotValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPotValue, "10000");
    lv_obj_set_style_text_color(ui_labelPotValue, lv_color_hex(0x8718E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPotValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPotValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Spinner2 = NULL;
    ui_Container1 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_labelSysInit = NULL;
    ui_labelPlatterRPM = NULL;
    ui_labelPlatterHz = NULL;
    ui_labelFrameCount = NULL;
    ui_labelFrameT = NULL;
    ui_labelFrameOnT = NULL;
    ui_Label1 = NULL;
    ui_labelState = NULL;
    ui_Label2 = NULL;
    ui_labelMotorEnabled = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_labelRotPeriod = NULL;
    ui_Label13 = NULL;
    ui_Label12 = NULL;
    ui_labelStrobeEnabled = NULL;
    ui_Label14 = NULL;
    ui_labelTemp1 = NULL;
    ui_labelTemp1Unit = NULL;
    ui_Label15 = NULL;
    ui_labelTemp2 = NULL;
    ui_labelTemp2Unit = NULL;
    ui_Label16 = NULL;
    ui_labelLight1 = NULL;
    ui_Label17 = NULL;
    ui_labelLight2 = NULL;
    ui_Label18 = NULL;
    ui_labelStrobeMode = NULL;
    ui_Label19 = NULL;
    ui_labelMotorMode = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_labelMotorMode1 = NULL;
    ui_labelStealthChop = NULL;
    ui_Label22 = NULL;
    ui_labelPlatterID = NULL;
    ui_Label23 = NULL;
    ui_labelPlatterID1 = NULL;
    ui_Label24 = NULL;
    ui_labelPlatterID2 = NULL;
    ui_Label25 = NULL;
    ui_labelFan1 = NULL;
    ui_Label26 = NULL;
    ui_labelFan2 = NULL;
    ui_Label27 = NULL;
    ui_labelPotValue = NULL;

}
