// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: helloWorld

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_labelSysInit;
extern lv_obj_t * ui_labelPlatterRPM;
extern lv_obj_t * ui_labelPlatterHz;
extern lv_obj_t * ui_labelFrameCount;
extern lv_obj_t * ui_labelFrameT;
extern lv_obj_t * ui_labelFrameOnT;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_labelState;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_labelMotorEnabled;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_labelRotPeriod;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_labelStrobeEnabled;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_labelTemp1;
extern lv_obj_t * ui_labelTemp1Unit;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_labelTemp2;
extern lv_obj_t * ui_labelTemp2Unit;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_labelLight1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_labelLight2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_labelStrobeMode;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_labelMotorMode;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_labelMotorMode1;
extern lv_obj_t * ui_labelStealthChop;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_labelPlatterID;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_labelPlatterID1;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_labelPlatterID2;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_labelFan1;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_labelFan2;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_labelPotValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

